services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --init-file /db-init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306 # MySQL na porta 3307
    volumes:
      - type: bind
        source: ./scripts/mysql/mysql-organizacao-DDL-DML.sql
        target: /db-init.sql
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    command: /bin/bash ./entrypoint.sh
    environment:
      SA_PASSWORD: "My_secret_!2#4%"
      ACCEPT_EULA: "Y"
    ports:
      - 1434:1433 # SQL Server na porta 1434
    volumes:
      - type: bind
        source: ./scripts/sqlserver/sqlserver-organizacao-DDL.sql
        target: /db-init.sql
      - type: bind
        source: ./scripts/sqlserver/entrypoint.sh
        target: /entrypoint.sh
      - type: bind
        source: ./scripts/sqlserver/db-init.sh
        target: /db-init.sh
  kafka-cluster:
    image: lensesio/fast-data-dev
    environment:
      ADV_HOST: 127.0.0.1
      RUNTESTS: 0
    ports:
      - 2181:2181 # Zookeeper
      - 9092:9092 # Kafka Broker
      - 8081-8083:8081-8083 # REST Proxy, Schema Registry, Kafka Connect
      - 9581-9585:9581-9585 # JMX Ports
      - 3030:3030 # UI
