services:
  kafka-cluster:
    image: lensesio/fast-data-dev
    environment:
      ADV_HOST: 127.0.0.1
      RUNTESTS: 0
      SAMPLEDATA: 0
      RUNNING_SAMPLEDATA: 0
    ports:
      - 2181:2181 # Zookeeper
      - 9092:9092 # Kafka Broker
      - 8081-8083:8081-8083 # REST Proxy, Schema Registry, Kafka Connect
      - 9581-9585:9581-9585 # JMX Ports
      - 3030:3030 # UI
